[package]
name = "pingpong"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "*", features = ["full"] }
iroh = "*"
async-channel = "2.5.0"
iced = "0.13.1"
pin-project = "1.1.10"
